kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-models
  namespace: redhat-ods-applications
stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_S3_BUCKET: "models"
  AWS_S3_ENDPOINT: "http://minio-service.minio.svc.cluster.local:9000"
  AWS_SECRET_ACCESS_KEY: "minio123"
type: Opaque
