kind: Secret
apiVersion: v1
metadata:
  name: dsp-secret
  namespace: ci-cd
stringData:
  conf.json: |
    {
      "host": "https://ds-pipeline-pipelines-definition-production-project.apps.{{ .Values.clusterdomainurl }}",
      "token": "TOKEN"
    }
type: Opaque
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-repo-kfp
  namespace: ci-cd
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manifest-repo-kfp
  namespace: ci-cd
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ml-pipeline-ci-cd-kfp
  namespace: ci-cd
spec:
  tasks:
    - name: git-clone-code-repo
      params:
        - name: url
          value: 'REPO_URL'
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'false'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: code-repository
    - name: git-push
      params:
        - name: BASE_IMAGE
          value: >-
            cgr.dev/chainguard/git:root-2.39@sha256:7759f87050dd8bacabe61354d75ccd7f864d6b6f8ec42697db7159eccd491139
        - name: GIT_USER_NAME
          value: CI-Pipeline
        - name: GIT_USER_EMAIL
          value: CI-Pipeline@openshift.com
        - name: GIT_SCRIPT
          value: >
            git config --global --add safe.directory /workspace/source && git
            add -A && git commit -m "added new pipeline manifest version"
            --allow-empty && git push origin HEAD:main
        - name: USER_HOME
          value: /home/git
        - name: VERBOSE
          value: 'true'
      runAfter:
        - upload-pipeline
      taskRef:
        kind: ClusterTask
        name: git-cli
      workspaces:
        - name: source
          workspace: manifest-repository
        - name: input
          workspace: manifest-repository
    - name: git-clone-manifest-repo
      params:
        - name: url
          value: 'REPO_URL'
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'false'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: manifest-repository
    - name: upload-pipeline
      params:
        - name: manifest-location
          value: model_training_kfp_pipeline.yaml
        - name: pipeline_name
          value: kfp-sample-pipeline
      runAfter:
        - compile-kfp-pipeline
      taskRef:
        kind: Task
        name: upload-pipeline
      workspaces:
        - name: manifest-repository
          workspace: manifest-repository
    - name: compile-kfp-pipeline
      params:
        - name: pipeline-location
          value: model_training_kfp_pipeline.py
        - name: manifest-location
          value: model_training_kfp_pipeline.yaml
      runAfter:
        - git-clone-code-repo
        - git-clone-manifest-repo
      taskRef:
        kind: Task
        name: compile-kfp-pipeline
      workspaces:
        - name: code-repository
          workspace: code-repository
        - name: manifest-repository
          workspace: manifest-repository
  workspaces:
    - name: code-repository
    - name: manifest-repository
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-kfp-pipeline-repo
  namespace: ci-cd
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ml-pipeline-ci-cd-kfp-
        labels:
          tekton.dev/pipeline: ml-pipeline-ci-cd-kfp
        namespace: ci-cd
      spec:
        params: []
        pipelineRef:
          name: ml-pipeline-ci-cd-kfp
        resources: []
        status: null
        workspaces:
          - name: code-repository
            persistentVolumeClaim:
              claimName: code-repo-kfp
          - name: manifest-repository
            persistentVolumeClaim:
              claimName: manifest-repo-kfp
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-kfp-pipeline-repo
  namespace: ci-cd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-kfp-pipeline-repo
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-event-listener-kfp-pipeline-repo
  namespace: ci-cd
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: el-event-listener-kfp-pipeline-repo
spec:
  to:
    kind: Service
    name: el-event-listener-kfp-pipeline-repo
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None