kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: elyra-spark-notebook
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'elyra-spark-notebook:v0.1.0'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      env:
        - name: KF_DEPLOYMENT_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: KF_DEPLOYMENT_NAMESPACE
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: AWS_SECRET_ACCESS_KEY
        - name: COS_BUCKET
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: COS_BUCKET
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: S3_ENDPOINT_URL
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/mamurak/os-mlops.git'
    contextDir: '/container-images/elyra-spark-notebook'
  runPolicy: Serial
