kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: elyra-notebook
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "elyra-notebook:v0.1.0"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      env:
        - name: KF_DEPLOYMENT_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: KF_DEPLOYMENT_NAMESPACE
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: AWS_SECRET_ACCESS_KEY
        - name: COS_BUCKET
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: COS_BUCKET
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: elyra-runtime
              key: S3_ENDPOINT_URL
              #     set URLs of Elyra bootstrap artifacts if deploying in air-gapped environments
              #
              #  - name: ELYRA_BOOTSTRAP_SCRIPT_URL
              #    valueFrom:
              #      secretKeyRef:
              #        name: elyra-runtime
              #        key: ELYRA_BOOTSTRAP_SCRIPT_URL
              #  - name: ELYRA_PIP_CONFIG_URL
              #    valueFrom:
              #      secretKeyRef:
              #        name: elyra-runtime
              #        key: ELYRA_PIP_CONFIG_URL
              #  - name: ELYRA_REQUIREMENTS_URL
              #    valueFrom:
              #      secretKeyRef:
              #        name: elyra-runtime
              #        key: ELYRA_REQUIREMENTS_URL
              #  - name: ELYRA_REQUIREMENTS_URL_PY37
              #    valueFrom:
              #      secretKeyRef:
              #        name: elyra-runtime
              #        key: elyra_requirements_url_py37
              #
              #     set target domains or IP for bypassing proxy
              #
              # - name: NO_PROXY
              #   value:
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/mamurak/os-mlops.git"
    contextDir: "/container-images/elyra-notebook"
  runPolicy: Serial
