kind: Secret
apiVersion: v1
metadata:
  name: elyra-runtime
stringData:
  AWS_ACCESS_KEY_ID: CHANGE_ME
  AWS_SECRET_ACCESS_KEY: CHANGE_ME
  COS_BUCKET: CHANGE_ME
  KF_DEPLOYMENT_NAMESPACE: CHANGE_ME
  S3_ENDPOINT_URL: CHANGE_ME
  #   set URLs of Elyra artifacts if deploying in air-gapped environment
  # ELYRA_BOOTSTRAP_SCRIPT_URL: CHANGE_ME
  # ELYRA_PIP_CONFIG_URL: CHANGE_ME
  # ELYRA_REQUIREMENTS_URL: CHANGE_ME
  # elyra_requirements_url_py37: CHANGE_ME
