apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-podmonitor
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /prometheus
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: seldon-core
