kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Face recognition"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular face recognition.
  name: face-recognition
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.3"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:face-recognition-v1.0.3
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"opencv","version":"4.6.0.66"},{"name":"face-recognition","version":"1.3.0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Code Server CUDA Data Science"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with VS Code application.
  name: code-server-cuda-data-science
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-code-server-ubi9-py39_2023b_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"code-server","version":"4.9.0"},{"name":"cuda","version":"11.8.0"},{"name":"cudnn","version":"8.6.0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Spark"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with PySpark.
  name: spark
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.1"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:spark-v1.0.1
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"pyspark","version":"3.3.1"},{"name":"hadoop","version":"3.3.4"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "OptaPy"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with OptaPy.
  name: optapy
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:jupyter-optapy-ubi9-py39_2023a_20230101
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"optapy","version":"8.31.1b0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "RStudio CUDA Data Science"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image RStudio application.
  name: rstudio-cuda-data-science
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-rstudio-c9s-py39_2023b_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"rstudio","version":"2022.07.2-576"},{"name":"cuda","version":"11.8.0"},{"name":"cudnn","version":"8.6.0"}]
        opendatahub.io/notebook-software: '[{"name":"R","version":"4.2.2"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Monai"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with Monai.
  name: monai
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023a"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:jupyter-monai-c9s-py39_2023a_20230101
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"monai","version":"1.1.0"},{"name":"opencv","version":"4.7.0"},{"name":"torch","version":"1.13.1"},{"name":"elyra","version":"3.14.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Object detection"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular object detection.
  name: object-detection
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.0"
      from:
        kind: DockerImage
        name: quay.io/eercan/object-detection-workbench:v1.0.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"opencv","version":"4.8.0.74"},{"name":"ultralytics","version":"8.0.130"},{"name":"onnxruntime","version":"1.15.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Trino"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling data integration through Trino and Starburst.
  name: trino
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.0"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:trino-v1.0.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"trino","version":"0.323.0"},{"name":"scikit-learn","version":"0.24.2"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.9"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Codeflare notebook"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling distributed model training with Codeflare.
  name: codeflare
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "0.1.0"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:codeflare-v0.1.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"codeflare-sdk","version":"0.10.1"},{"name":"torch","version":"1.13.1"},{"name":"ray","version":"2.7.0"},{"name":"scikit-learn","version":"1.1.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Fraud detection notebook"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image for running the fraud detection demo.
  name: fraud-detection
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.0.1"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/workbenches:fraud-detection-v1.0.1
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"tensorflow","version":"2.11.1"},{"name":"scikit-learn","version":"1.2.2"},{"name":"trino","version":"0.323.0"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Langchain notebook"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with the Langchain stack.
  name: langchain
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023c"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-jupyter-langchain-c9s-py311_2023c_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"langchain","version":"0.0.281"},{"name":"torch","version":"2.0.1"},{"name":"codeflare-sdk","version":"0.7.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Langflow notebook"
    opendatahub.io/notebook-image-desc: >-
      Workbench image with the Langflow IDE.
  name: langflow
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "2023c"
      from:
        kind: DockerImage
        name: quay.io/opendatahub-contrib/workbench-images:cuda-langflow-langflow-c9s-py39_2023c_latest
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"langflow","version":"0.4.18"},{"name":"langchain","version":"0.0.256"},{"name":"torch","version":"2.0.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: ''
    opendatahub.io/notebook-image-name: VS Code with KFP
  name: vscode-kfp
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.1.2
      annotations:
        opendatahub.io/notebook-python-dependencies: '[]'
        opendatahub.io/notebook-software: '[]'
        openshift.io/imported-from: 'quay.io/mmurakam/workbenches:vscode-kfp-v0.1.2'
      from:
        kind: DockerImage
        name: 'quay.io/mmurakam/workbenches:vscode-kfp-v0.1.2'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source