apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: anomaly-detection-models
  namespace: odh-applications
  finalizers:
    - objectbucket.io/finalizer
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: anomaly-detection-models
  objectBucketName: obc-odh-applications-anomaly-detection-models
  storageClassName: openshift-storage.noobaa.io
