kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pachyderm-notebook-role
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - pachyderm-notebook-scc
